apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-reverser-config
  namespace: {{ .Release.Namespace | default "apps-prod" }}
  labels:
    app.kubernetes.io/name: ip-reverser-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}