apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          env:
            # ConfigMap values
            {{- range $key, $value := .Values.configMap.data }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: ip-reverser-config
                  key: {{ $key }}
            {{- end }}

            # Secret (DB URL)
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ip-reverser-secrets
                  key: database-url

            # Extra env vars from values.yaml
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              {{- if and (kindIs "map" $value) (hasKey $value "secretName") }}
                valueFrom:
                  secretKeyRef:
                    name: {{ $value.secretName }}
                    key: {{ $value.secretKey }}
              {{- else }}
                value: {{ $value | quote }}
              {{- end }}
            {{- end }}
