apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ip-reverser-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: ip-reverser-app
    app.kubernetes.io/part-of: argocd
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Oluwaseun2003/reversed-ip-app
    targetRevision: main
    path: helm
    helm:
      releaseName: ip-reverser-app
      valueFiles:
        - values.yaml
      parameters:
        - name: global.environment
          value: production
        - name: deployment.replicaCount
          value: "3"
        - name: autoscaling.minReplicas
          value: "3"
        - name: autoscaling.maxReplicas
          value: "10"
        - name: deployment.container.resources.limits.cpu
          value: "1000m"
        - name: deployment.container.resources.limits.memory
          value: "1Gi"

  destination:
    server: https://kubernetes.default.svc
    namespace: apps-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data/deploymentTime
