global:
  # Environment (dev, staging, prod)
  environment: staging
  imagePullPolicy: IfNotPresent

# Application image configuration
image:
  repository: docker.io/oluwaseun1511/ip-reverser-app
  tag: "latest"
  pullPolicy: IfNotPresent

deployment:
  replicaCount: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  
  # Container configuration
  container:
    port: 3001
    
    # Resource limits and requests
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    
    livenessProbe:
      httpGet:
        path: /health
        port: 3001
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    
    # Readiness probe
    readinessProbe:
      httpGet:
        path: /health
        port: 3001
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    
    # Startup probe
    startupProbe:
      httpGet:
        path: /health
        port: 3001
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1

# Environment variables
env:
  NODE_ENV: production
  PORT: 3001
  CORS_ORIGIN: "*"
  DATABASE_URL:
    secretName: ip-reverser-secrets
    secretKey: database-url

# Service configuration
service:
  type: LoadBalancer
  port: 80
  targetPort: 3001
  annotations: {}
  # For AWS Load Balancer:
  # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  # service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  # For AWS ALB:
  # kubernetes.io/ingress.class: "alb"
  # alb.ingress.kubernetes.io/scheme: "internet-facing"
  # alb.ingress.kubernetes.io/target-type: "ip"
  # For GCP:
  # kubernetes.io/ingress.global-static-ip-name: "ip-reverser-ip"
  # networking.gke.io/managed-certificates: "ip-reverser-ssl"
  # kubernetes.io/ingress.allow-http: "false"
  hosts:
    - host: api.your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # - secretName: ip-reverser-tls
  #   hosts:
  #     - api.your-domain.com

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Pod Security Context
podSecurityContext:
  fsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001

# Security Context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001
  capabilities:
    drop:
      - ALL

# ConfigMap data
configMap:
  data:
    NODE_ENV: "production"
    PORT: "3001"
    CORS_ORIGIN: "*"

# Secret data (base64 encoded values)
secrets:
  database-url: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQGhvc3QuZG9ja2VyLmludGVybmFsOjU0MzMvaXByZXZlcnNlcg=="

# PostgreSQL dependency
postgresql:
  enabled: true
  auth:
    postgresPassword: "your-postgres-password"
    username: "postgres"
    password: "password"
    database: "ipreverser"
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi

# Service Monitor
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  path: /metrics
  labels:
    app: ip-reverser-app

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Network Policy
networkPolicy:
  enabled: false
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: 3001

labels: {}
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
deploymentTime: "2025-08-18T13:52:34Z"
